### ISSUE TITLE
What does this plugin do?

### ISSUE THREAD

**Issue by remotevase** [PocketEssential/InvisibilitySystem#1]
Not much progress has been made. Please try to keep all repositories ACTIVE, unless the plugin is completed. In addition, each readme should ideally have a **detailed description** of _exactly what the plugin is supposed to do_ so that other devs can help to complete the plugin if you are not available

**Comment by ghost** [comment]
I think (By looking at the source) this plugin makes the normal mcpe player (not vip) invisible on join!

**Comment by remotevase** [comment]
hmm okay... it's a little confusing lol

**Comment by xZeroMCPE** [comment]
lolz
